CREATE TABLE MEDICAL_RECORD (
	ID NUMBER
);
COMMENT ON TABLE MEDICAL_RECORS IS '진료기록';
COMMENT ON COLUMN MEDICAL_RECORS.ID IS '기록번호';

-- ERD클라우드 이용해서 테이블 3개 만들고 
-- 디비버에서 3행씩 INSERT한다음  우리반 게시판 과제탭에 올리기
/*
CREATE TABLE "MEMBER" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"MEMBER_NAME"	VARCHAR(20)		NOT NULL,
	"EMAIL"	VARCHAR(200)		NOT NULL
);

CREATE TABLE "RENTAL" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"BOOK_NO"	NUMBER		NOT NULL,
	"RENTAL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"RENTAL_NO"	NUMBER		NOT NULL
);

CREATE TABLE "BOOK" (
	"BOOK_NO"	NUMBER		NOT NULL,
	"BOOK_NAME"	VARCHAR(500)		NOT NULL,
	"PUBLISHER"	VARCHAR(300)		NOT NULL
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEMBER_NO"
);

ALTER TABLE "RENTAL" ADD CONSTRAINT "PK_RENTAL" PRIMARY KEY (
	"MEMBER_NO",
	"BOOK_NO"
);

ALTER TABLE "BOOK" ADD CONSTRAINT "PK_BOOK" PRIMARY KEY (
	"BOOK_NO"
);

ALTER TABLE "RENTAL" ADD CONSTRAINT "FK_MEMBER_TO_RENTAL_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "RENTAL" ADD CONSTRAINT "FK_BOOK_TO_RENTAL_1" FOREIGN KEY (
	"BOOK_NO"
)
REFERENCES "BOOK" (
	"BOOK_NO"
);
*/

/*
 * < VIEW 뷰 > 
 * SELECT문을 저장하는 가상의 테이블
 * 실제 데이터를 저장하는 것이 아니라, SQL문만 저장해 두었다가
 * 조회 시점에 저장한 SQL문을 실행시켜서 결과를 보여줌
 * 
 * CREATE VIEW 뷰이름
 * 		AS 서브쿼리;
 * 
 * - OR REPLACE : 뷰가 이미 존재하면 덮어쓰기
 */

GRANT CREATE VIEW TO C##MS;
-- < 뷰 만들기 >
CREATE VIEW VW_ANIMAL_INFO
    AS
SELECT 
		K.KEEPER_NAME
	  , A.ANIMAL_NAME
	  , S.SPECIES_NAME
	  , Z.ZONE_NAME
	  , A.WEIGHT_KG
	  , DECODE(A.GENDER, 'M', '수컷', 'F', '암컷')
  FROM
  		KEEPER K
  LEFT
  JOIN
  		ANIMAL A USING(KEEPER_ID)
  LEFT
  JOIN
  		ZONE Z USING(ZONE_ID)
  LEFT
  JOIN
  		SPECIES S USING(SPECIES_ID)

 SELECT * FROM VW_ANIMAL_INFO
  WHERE KEEPER_NAME = '제인구달'
  ORDER
  	 BY
  	 	ANIMAL_NAME;

-- 데이터 딕셔너리
SELECT * FROM USER_VIEWS;
SELECT * FROM USER_CONSTRAINTS;
SELECT * FROM USER_TAB_COLUMNS;
SELECT * FROM USER_TABLE;
SELECT * FROM USER_CATALOG;
SELECT * FROM USER_OBJECTS;
SELECT * FROM DICTIONARY;

-----------------------------------------------------------
/*
 * 단순 뷰(1개 테이블, 함수/그룹핑 없음) 는 DML 가능
 * 복합 뷰(JOIN, GROUP BY등) DML 불가
 * 보통 만들 떄 WITH READ ONLY 옵션을 줘서 DML자체를 차단
 */

-- 구역뱔 통계 SELECT

CREATE OR REPLACE VIEW VW_ZONE_STATS
AS
SELECT 
		ZONE_NAME
	  , COUNT(*) "COUNT"
	  , MAX(WEIGHT_KG) "MAX_WEIGHT"
	  , MIN(WEIGHT_KG) "MIN_WEIGHT"
  FROM
  		ANIMAL
  JOIN
  		ZONE USING(ZONE_ID)
  GROUP 
  	 BY 
  	 	ZONE_NAME
   WITH READ ONLY;

SELECT * FROM VW_ZONE_STATS;
  		
-- 뷰의 장점 
-- 1. 재사용성 : 자주쓰는 쿼리를 저장 -> 복잡한 쿼리를 간단하게 사용가능
-- 2. 보안성 : 원하는 컬럼만 노출 가능

-- < 뷰 삭제 > 

DROP VIEW 뷰이름;





























